# Coding Domains Of Life

## Background information

[Tree Of Life](https://www.evogeneao.com/en/learn/tree-of-life)
![](../images/tree-of-life_2000.png)

[Genetic Code](https://www.geeksforgeeks.org/biology/genetic-code-molecular-basis-of-inheritance/)
![](../images/Genetic-Code.webp)

## Data source and description

### Source

[UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/dataset/577/codon+usage)

### Variable description

In [56]:
with option_context('display.max_colwidth', None):
    display(
        DataFrame(
            {
                'Column': '1 2 3 4 5 6-69'.split(),
                'Variable': 'Kingdom DNAtype SpeciesID Ncodons SpeciesName codon'.split(),
                'Description': [
                    "A 3-letter code corresponding to 'xxx' in the CUTG database name: 'arc'(archaea), 'bct'(bacteria), 'phg'(bacteriophage), 'plm' (plasmid), 'pln' (plant), 'inv' (invertebrate), 'vrt' (vertebrate), 'mam' (mammal), 'rod' (rodent), 'pri' (primate), and 'vrl'(virus) sequence entries. Note that the CUTG database does not contain 'arc' and 'plm' (these have been manually curated ourselves).",
                    "An integer for the genomic composition in the species: 0-genomic, 1-mitochondrial, 2-chloroplast, 3-cyanelle, 4-plastid, 5-nucleomorph, 6-secondary_endosymbiont, 7-chromoplast, 8-leucoplast, 9-NA, 10-proplastid, 11-apicoplast, and 12-kinetoplast.",
                    "An integer, which uniquely indicates the entries of an organism. It is an accession identifier for each different species in the original CUTG database, followed by the first item listed in each genome.",
                    "The algebraic sum of the numbers listed for the different codons in an entry of CUTG. Codon frequencies are normalized to the total codon count, hence the number of occurrences divided by 'Ncodons' is the codon frequencies listed in the data file.",
                    "Descriptive label of the name of the species.",
                    "header: codon; entries: frequency of usage (5 digit floating point number)."
                ]
            },
        ).set_index('Column')
    )

           Variable                                                                                                                                                                                                                                                                                                                                                                                        Description
Column
1           Kingdom  A 3-letter code corresponding to 'xxx' in the CUTG database name: 'arc'(archaea), 'bct'(bacteria), 'phg'(bacteriophage), 'plm' (plasmid), 'pln' (plant), 'inv' (invertebrate), 'vrt' (vertebrate), 'mam' (mammal), 'rod' (rodent), 'pri' (primate), and 'vrl'(virus) sequence entries. Note that the CUTG database does not contain 'arc' and 'plm' (these have been manually curated ourselves).
2           DNAtype                                                                                                                                             An integer for the genomic composition in the species: 0-genomic, 1-mitochondrial, 2-chloroplast, 3-cyanelle, 4-plastid, 5-nucleomorph, 6-secondary_endosymbiont, 7-chromoplast, 8-leucoplast, 9-NA, 10-proplastid, 11-apicoplast, and 12-kinetoplast.
3         SpeciesID                                                                                                                                                                                         An integer, which uniquely indicates the entries of an organism. It is an accession identifier for each different species in the original CUTG database, followed by the first item listed in each genome.
4           Ncodons                                                                                                                                            The algebraic sum of the numbers listed for the different codons in an entry of CUTG. Codon frequencies are normalized to the total codon count, hence the number of occurrences divided by 'Ncodons' is the codon frequencies listed in the data file.
5       SpeciesName                                                                                                                                                                                                                                                                                                                                                      Descriptive label of the name of the species.
6-69          codon                                                                                                                                                                                                                                                                                                                        header: codon; entries: frequency of usage (5 digit floating point number).

## First look

In [26]:
from pandas import read_csv, DataFrame, option_context

### Load csv and fix Dtypes

In [10]:
# Load CSV
df = read_csv('../data/codon_usage.csv', low_memory=False)

display(df.head())
print(df.info())

  Kingdom  DNAtype  SpeciesID  Ncodons  ...      GAG      UAA      UAG      UGA
0     vrl        0     100217     1995  ...  0.04361  0.00251  0.00050  0.00000
1     vrl        0     100220     1474  ...  0.04410  0.00271  0.00068  0.00000
2     vrl        0     100755     4862  ...  0.02468  0.00391  0.00000  0.00144
3     vrl        0     100880     1915  ...  0.03446  0.00261  0.00157  0.00000
4     vrl        0     100887    22831  ...  0.03679  0.00000  0.00044  0.00131

[5 rows x 69 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13028 entries, 0 to 13027
Data columns (total 69 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Kingdom      13028 non-null  object
 1   DNAtype      13028 non-null  int64
 2   SpeciesID    13028 non-null  int64
 3   Ncodons      13028 non-null  int64
 4   SpeciesName  13028 non-null  object
 5   UUU          13028 non-null  object
 6   UUC          13028 non-null  object
 7   UUA          13028 non-null  float64
 8   UUG          13028 non-null  float64
 9   CUU          13028 non-null  float64
 10  CUC          13028 non-null  float64
 11  CUA          13028 non-null  float64
 12  CUG          13028 non-null  float64
 13  AUU          13028 non-null  float64
 14  AUC          13028 non-null  float64
 15  AUA          13028 non-null  float64
 16  AUG          13028 non-null  float64
 17  GUU          13028 non-null  float64
 18  GUC          13028 non-null  float64
 19  GUA          13028 non-null  float64
 20  GUG          13028 non-null  float64
 21  GCU          13028 non-null  float64
 22  GCC          13028 non-null  float64
 23  GCA          13028 non-null  float64
 24  GCG          13028 non-null  float64
 25  CCU          13028 non-null  float64
 26  CCC          13028 non-null  float64
 27  CCA          13028 non-null  float64
 28  CCG          13028 non-null  float64
 29  UGG          13028 non-null  float64
 30  GGU          13028 non-null  float64
 31  GGC          13028 non-null  float64
 32  GGA          13028 non-null  float64
 33  GGG          13028 non-null  float64
 34  UCU          13028 non-null  float64
 35  UCC          13028 non-null  float64
 36  UCA          13028 non-null  float64
 37  UCG          13028 non-null  float64
 38  AGU          13028 non-null  float64
 39  AGC          13028 non-null  float64
 40  ACU          13028 non-null  float64
 41  ACC          13028 non-null  float64
 42  ACA          13028 non-null  float64
 43  ACG          13028 non-null  float64
 44  UAU          13028 non-null  float64
 45  UAC          13028 non-null  float64
 46  CAA          13028 non-null  float64
 47  CAG          13028 non-null  float64
 48  AAU          13028 non-null  float64
 49  AAC          13028 non-null  float64
 50  UGU          13028 non-null  float64
 51  UGC          13028 non-null  float64
 52  CAU          13028 non-null  float64
 53  CAC          13028 non-null  float64
 54  AAA          13028 non-null  float64
 55  AAG          13028 non-null  float64
 56  CGU          13028 non-null  float64
 57  CGC          13028 non-null  float64
 58  CGA          13028 non-null  float64
 59  CGG          13028 non-null  float64
 60  AGA          13028 non-null  float64
 61  AGG          13028 non-null  float64
 62  GAU          13028 non-null  float64
 63  GAC          13028 non-null  float64
 64  GAA          13028 non-null  float64
 65  GAG          13028 non-null  float64
 66  UAA          13028 non-null  float64
 67  UAG          13028 non-null  float64
 68  UGA          13028 non-null  float64
dtypes: float64(62), int64(3), object(4)
memory usage: 6.9+ MB
None

In [14]:
# Find probematic values in the 'object' codon columns
display(df[~df.UUU.str.startswith('0')])
display(df[~df.UUC.str.startswith('0')])

     Kingdom  DNAtype  SpeciesID  Ncodons  ...      GAG      UAA      UAG      UGA
486      vrl        0      12440     1238  ...  0.02423  0.02262  0.00162  0.00000
5063     bct        0     353569     1698  ...  0.02356  0.04476  0.02473  0.00118

[2 rows x 69 columns]

     Kingdom  DNAtype  SpeciesID  Ncodons  ...      GAG      UAA      UAG      UGA
5063     bct        0     353569     1698  ...  0.02356  0.04476  0.02473  0.00118

[1 rows x 69 columns]

In [19]:
# Keep only the good records
df = df[df.UUU.str.startswith('0')]
df = df.astype({'UUU': float, 'UUC': float})

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13026 entries, 0 to 13027
Data columns (total 69 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Kingdom      13026 non-null  object
 1   DNAtype      13026 non-null  int64
 2   SpeciesID    13026 non-null  int64
 3   Ncodons      13026 non-null  int64
 4   SpeciesName  13026 non-null  object
 5   UUU          13026 non-null  float64
 6   UUC          13026 non-null  float64
 7   UUA          13026 non-null  float64
 8   UUG          13026 non-null  float64
 9   CUU          13026 non-null  float64
 10  CUC          13026 non-null  float64
 11  CUA          13026 non-null  float64
 12  CUG          13026 non-null  float64
 13  AUU          13026 non-null  float64
 14  AUC          13026 non-null  float64
 15  AUA          13026 non-null  float64
 16  AUG          13026 non-null  float64
 17  GUU          13026 non-null  float64
 18  GUC          13026 non-null  float64
 19  GUA          13026 non-null  float64
 20  GUG          13026 non-null  float64
 21  GCU          13026 non-null  float64
 22  GCC          13026 non-null  float64
 23  GCA          13026 non-null  float64
 24  GCG          13026 non-null  float64
 25  CCU          13026 non-null  float64
 26  CCC          13026 non-null  float64
 27  CCA          13026 non-null  float64
 28  CCG          13026 non-null  float64
 29  UGG          13026 non-null  float64
 30  GGU          13026 non-null  float64
 31  GGC          13026 non-null  float64
 32  GGA          13026 non-null  float64
 33  GGG          13026 non-null  float64
 34  UCU          13026 non-null  float64
 35  UCC          13026 non-null  float64
 36  UCA          13026 non-null  float64
 37  UCG          13026 non-null  float64
 38  AGU          13026 non-null  float64
 39  AGC          13026 non-null  float64
 40  ACU          13026 non-null  float64
 41  ACC          13026 non-null  float64
 42  ACA          13026 non-null  float64
 43  ACG          13026 non-null  float64
 44  UAU          13026 non-null  float64
 45  UAC          13026 non-null  float64
 46  CAA          13026 non-null  float64
 47  CAG          13026 non-null  float64
 48  AAU          13026 non-null  float64
 49  AAC          13026 non-null  float64
 50  UGU          13026 non-null  float64
 51  UGC          13026 non-null  float64
 52  CAU          13026 non-null  float64
 53  CAC          13026 non-null  float64
 54  AAA          13026 non-null  float64
 55  AAG          13026 non-null  float64
 56  CGU          13026 non-null  float64
 57  CGC          13026 non-null  float64
 58  CGA          13026 non-null  float64
 59  CGG          13026 non-null  float64
 60  AGA          13026 non-null  float64
 61  AGG          13026 non-null  float64
 62  GAU          13026 non-null  float64
 63  GAC          13026 non-null  float64
 64  GAA          13026 non-null  float64
 65  GAG          13026 non-null  float64
 66  UAA          13026 non-null  float64
 67  UAG          13026 non-null  float64
 68  UGA          13026 non-null  float64
dtypes: float64(64), int64(3), object(2)
memory usage: 7.0+ MB

### Check column values

In [38]:
df.describe(include='all')

       Kingdom       DNAtype  ...           UAG           UGA
count    13026  13026.000000  ...  13026.000000  13026.000000
unique      11           NaN  ...           NaN           NaN
top        bct           NaN  ...           NaN           NaN
freq      2919           NaN  ...           NaN           NaN
mean       NaN      0.367265  ...      0.000590      0.006179
std        NaN      0.688764  ...      0.000882      0.010345
min        NaN      0.000000  ...      0.000000      0.000000
25%        NaN      0.000000  ...      0.000000      0.000410
50%        NaN      0.000000  ...      0.000420      0.001130
75%        NaN      1.000000  ...      0.000830      0.002890
max        NaN     12.000000  ...      0.025610      0.106700

[11 rows x 69 columns]

In [31]:
# Print unique values
with option_context('display.max_rows', 100, 'display.max_colwidth', 100):
    display( DataFrame(
        [ [sorted(df[c].unique())] if (_ := df[c].nunique()) < 15 else [_] for c in df.columns ],
        index=df.columns).rename(columns={0:'values'}
    ))

                                                              values
Kingdom      [arc, bct, inv, mam, phg, plm, pln, pri, rod, vrl, vrt]
DNAtype                          [0, 1, 2, 3, 4, 5, 6, 7, 9, 11, 12]
SpeciesID                                                      12366
Ncodons                                                         7103
SpeciesName                                                    13014
UUU                                                             4789
UUC                                                             4119
UUA                                                             4796
UUG                                                             3282
CUU                                                             3677
CUC                                                             4389
CUA                                                             4063
CUG                                                             4562
AUU                                                             5243
AUC                                                             4684
AUA                                                             4477
AUG                                                             3236
GUU                                                             3640
GUC                                                             3602
GUA                                                             3149
GUG                                                             3993
GCU                                                             3724
GCC                                                             5043
GCA                                                             3451
GCG                                                             3558
CCU                                                             2751
CCC                                                             3221
CCA                                                             3488
CCG                                                             2889
UGG                                                             2597
GGU                                                             3622
GGC                                                             4391
GGA                                                             3538
GGG                                                             2613
UCU                                                             3273
UCC                                                             2996
UCA                                                             3391
UCG                                                             2306
AGU                                                             2440
AGC                                                             2565
ACU                                                             3253
ACC                                                             4188
ACA                                                             4170
ACG                                                             2484
UAU                                                             3977
UAC                                                             3002
CAA                                                             3670
CAG                                                             3724
AAU                                                             4661
AAC                                                             3675
UGU                                                             2205
UGC                                                             2195
CAU                                                             2615
CAC                                                             2668
AAA                                                             5288
AAG                                                             4532
CGU                                                             2297
CGC                                                             3181
CGA                                                             1879
CGG                                                             2135
AGA                                                             2835
AGG                                                             2228
GAU                                                             4577
GAC                                                             4416
GAA                                                             4827
GAG                                                             4686
UAA                                                              701
UAG                                                              421
UGA                                                             1786

In [37]:
# Count records per class of possible target variables
print(df.Kingdom.value_counts(normalize=True), '\n')
print(df.DNAtype.value_counts(normalize=True))

Kingdom
bct    0.224090
vrl    0.217335
pln    0.193690
vrt    0.159450
inv    0.103255
mam    0.043912
phg    0.016889
rod    0.016505
pri    0.013819
arc    0.009673
plm    0.001382
Name: proportion, dtype: float64

DNAtype
0     0.711270
1     0.222555
2     0.062644
4     0.002380
12    0.000384
5     0.000154
3     0.000154
11    0.000154
9     0.000154
6     0.000077
7     0.000077
Name: proportion, dtype: float64